### ISSUE TITLE
S3 - Unable to sync: Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by kriswill** [LevelbossMike/ember-deploy#30]
When attempting to upload static assets to S3, I receive the ECONNREFUSED error.
Here's what it looks like:
```sh
→ ember deploy:assets --environment staging 
version: 0.1.11
Uploading assets...
Unable to sync: Error: connect ECONNREFUSED
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete] (net.js:896:19)
```
My deploy.json looks about like this:
```json
{
  "staging": {
    "buildEnv": "staging",
    "store": {
      "host": "redacted.test",
      "port": 49155,
      "password": "XXX"
    },
    "assets": {
      "type": "s3",
      "gzip": true,
      "accessKeyId": "AAAAAAAAAAAAAAAAAAAA",
      "secretAccessKey": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "endpoint": "redacted.text.s3-website-us-west-1.amazonaws.com",
      "bucket": "redacted.test"
    }
  }
}
```

I tried multiple IAM accounts, and double-checked my S3 user policy:

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": ["s3:ListBucket"],
      "Resource": ["arn:aws:s3:::redacted.test"]
    },
    {
      "Effect": "Allow",
      "Action": [
        "s3:PutObject",
        "s3:GetObject",
        "s3:DeleteObject"
      ],
      "Resource": ["arn:aws:s3:::redacted.test/*"]
    }
  ]
}
```
And bucket policy:

```json
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Sid": "Allow Public Access to All Objects",
			"Effect": "Allow",
			"Principal": "*",
			"Action": "s3:GetObject",
			"Resource": "arn:aws:s3:::redacted.test/*"
		}
	]
}
```

**Comment by kriswill** [comment]
I solved it by adding "region" to my deploy.json:
```json 
{
    "assets": {
      "type": "s3",
      "gzip": true,
      "accessKeyId": "AAAAAAAAAAAAAAAAAAAA",
      "secretAccessKey": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "region": "us-west-1",
      "bucket": "redacted.test"
    }
}
```
